### ISSUE TITLE
Indentation NOT working

### ISSUE THREAD

**Issue by Walkwise-0** [diegoeis/obsidianotion#10]
Hi Diego, 

I love your theme, it's actually the only one I like among the many that are present in Obsidian and I almost can't do without it. 
I noticed that the indentation does not work anymore and it's a pity. I often use bullet lists of different levels and now, whenever I press the tab key, nothing happens. Or better, the bullet point symbol changes (as I have a snippet to have different symbols for different levels), but it is not indented and there are also no indentation lines. It works completely fine with the default time, but I'd hate switching back. Is it solvable? I have no experience coding and rely on you for this  💪🏻

Love from Italy.

<img width="358" alt="obsidian notion theme" src="https://github.com/diegoeis/obsidianotion/assets/167359558/c337a343-f997-4e47-ac1f-a6b4ceed04e5">
<img width="362" alt="default theme" src="https://github.com/diegoeis/obsidianotion/assets/167359558/ef151a93-153e-4a74-aaff-dba4c7e0c0c9">

**Comment by byuc** [comment]
I had the same problem and I look forward to solving it.

**Comment by byuc** [comment]
I had the same problem and I look forward to solving it.

**Comment by Walkwise-0** [comment]
Hi @byuc I managed to solve it, even though I couldn't find a way to display the indentation lines. Go to your .obisidan folder, then to the theme folder and copy the following code in your "theme.css" file. I hope it works for you as well ^^

[theme.txt](https://github.com/diegoeis/obsidianotion/files/15278938/theme.txt)

**Comment by byuc** [comment]
Hi @Walkwise-0 thanks for your reply.If you need to show presentation guides, you can do so by modifying theme.css in your theme file`.cm-indent:: before {border: 0! important;}`modified to`.cm-indent:: before {border: 1! important;}`。You can restore the show orientation guides.
Hope to help you.
