### ISSUE TITLE
[Bug] Preview mode theme does not match edit theme

### ISSUE THREAD

**Issue by Safayy** [diegoeis/obsidianotion#3]
Love the theme, it really makes Obsidian so much more clean feeling. Thanks for making this! I've tried many themes before an this feels so much neater.
I've noticed the preview texts don't match the edit texts. I use some plugins that make it look out of place, like Obsidian Columns. It reverts to the default theme. #2

**Comment by diegoeis** [comment]
@Safayy I just made some modifications right now. I think the edit and preview mode are very similar right now.
https://github.com/diegoeis/obsidianotion/commit/f6aa050efdf9c96c2f42d5091af8bb15d2b2c7c4
