### ISSUE TITLE
Indentation issues

### ISSUE THREAD

**Issue by git-nny** [diegoeis/obsidianotion#7]
Hey, absolutely love your theme! 

I noticed some issues with indentation since the last update. 
The tab key needs to be pressed two times, it doesn't indent bullet points correctly anymore. I've attached a screenshot, hope that helps! Thank you so much for your work!

![Screenshot 2024-02-13 211053](https://github.com/diegoeis/obsidianotion/assets/147989339/ff257eec-706b-4907-891b-e216c486b598)

**Comment by XiaoTonghuan** [comment]
I also find this problem @diegoeis

**Comment by diegoeis** [comment]
I think this is fixed now in the last version 1.1.33, can you test?
![Uploading obsidianotion.gif…]()

**Comment by XiaoTonghuan** [comment]
When I use shift + enter, It works well, but when I use tab or enter only, It doesn't work. 
This problem only exists in live-preview

**Comment by XiaoTonghuan** [comment]
@diegoeis 
![Uploading 动画.gif…]()

**Comment by diegoeis** [comment]
Closed with newest version 1.1.33.
