### ISSUE TITLE
Changes to the codeblock font style does not apply.

### ISSUE THREAD

**Issue by SreedevT** [diegoeis/obsidianotion#8]
No monospace font gets applied to the codeblock. The current font is not very readable. I do use the codestyler plugin but that dosent seem to be interfering with this setting.

**Comment by diegoeis** [comment]
I think this is monospaced. 
<img width="711" alt="image" src="https://github.com/diegoeis/obsidianotion/assets/1918210/eb7ebc70-b6d3-4064-9426-7b1d306fcb6c">
